/**
 * AI Transparency Module
 * Simple AI transparency utilities
 */

import type { AITransparencyInfo } from '../../types';

/**
 * Generate transparency information for AI content
 */
export function generateTransparencyInfo(
  isAI: boolean,
  modelName?: string,
  confidence?: number,
  humanOversight: boolean = false,
  explanation?: string
): AITransparencyInfo {
  return {
    isAI,
    modelName,
    confidence,
    humanOversight,
    explanation,
  };
}

/**
 * Check if content requires AI disclosure
 */
export function requiresAIDisclosure(content: string): boolean {
  const aiKeywords = [
    'ai-generated',
    'artificial intelligence',
    'machine learning',
    'algorithm',
    'automated',
    'generated by ai',
  ];

  const lowerContent = content.toLowerCase();
  return aiKeywords.some(keyword => lowerContent.includes(keyword));
}

/**
 * Generate AI disclosure text
 */
export function generateAIDisclosure(
  modelName?: string,
  confidence?: number,
  humanOversight: boolean = false
): string {
  let disclosure = 'This content may be generated by artificial intelligence.';

  if (modelName) {
    disclosure += ` Generated using ${modelName}.`;
  }

  if (confidence) {
    disclosure += ` Confidence level: ${Math.round(confidence * 100)}%.`;
  }

  if (humanOversight) {
    disclosure += ' This content has been reviewed by human oversight.';
  }

  disclosure += ' Please verify important information independently.';

  return disclosure;
}

/**
 * Validate AI transparency requirements
 */
export function validateTransparency(
  content: string,
  transparencyInfo: AITransparencyInfo
): { valid: boolean; violations: string[] } {
  const violations: string[] = [];

  // Check if AI content has proper disclosure
  if (transparencyInfo.isAI && !requiresAIDisclosure(content)) {
    violations.push('AI-generated content must include AI disclosure');
  }

  // Check if confidence is provided for AI content
  if (transparencyInfo.isAI && transparencyInfo.confidence === undefined) {
    violations.push('AI content should include confidence score');
  }

  // Check if human oversight is indicated
  if (transparencyInfo.isAI && !transparencyInfo.humanOversight) {
    violations.push('AI content should indicate human oversight status');
  }

  return {
    valid: violations.length === 0,
    violations,
  };
}

/**
 * Get transparency badge for UI
 */
export function getTransparencyBadge(transparencyInfo: AITransparencyInfo): {
  text: string;
  color: 'green' | 'yellow' | 'red';
  icon: string;
} {
  if (!transparencyInfo.isAI) {
    return {
      text: 'Human Generated',
      color: 'green',
      icon: '👤',
    };
  }

  if (transparencyInfo.humanOversight) {
    return {
      text: 'AI + Human Review',
      color: 'yellow',
      icon: '🤖👤',
    };
  }

  return {
    text: 'AI Generated',
    color: 'red',
    icon: '🤖',
  };
}
